# Generated by Django 4.1.5 on 2023-03-03 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('Tours', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seeker_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TripQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Provide_TripQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('including_hotel', models.BooleanField()),
                ('including_extra_activities', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider_profile_model')),
                ('trip_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.tripquotation')),
            ],
        ),
        migrations.CreateModel(
            name='city_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state_name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='seeker.state_data')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker_Profile_Model',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seeker.seeker_names')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/seeker_profile/avatar.jpeg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[450, 450], upload_to='seeker_profile/')),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10)),
                ('age', models.IntegerField(blank=True, default=15, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.city_data')),
            ],
        ),
    ]
