# Generated by Django 4.1.7 on 2023-03-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile_model',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.city_data'),
        ),
        migrations.DeleteModel(
            name='city_data',
        ),
        migrations.DeleteModel(
            name='state_data',
        ),
    ]
