# Generated by Django 4.1.5 on 2023-03-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_alter_seeker_profile_model_area_delete_city_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_hotel_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('number_of_rooms', models.IntegerField()),
                ('trip_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.tripquotation')),
            ],
        ),
    ]
