# Generated by Django 4.1.5 on 2023-03-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the city.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the country.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the destination.', max_length=100)),
                ('description', models.TextField(help_text='Enter a description of the destination.')),
                ('image', models.ImageField(help_text='Upload an image of the destination.', upload_to='destination_images/')),
                ('climate', models.CharField(help_text='Enter the climate of the destination.', max_length=100)),
                ('language', models.CharField(help_text='Enter the primary language spoken in the destination.', max_length=100)),
                ('currency', models.CharField(help_text='Enter the currency used in the destination.', max_length=100)),
                ('timezone', models.CharField(help_text='Enter the timezone of the destination.', max_length=100)),
                ('visa_required', models.BooleanField(default=False, help_text='Check if a visa is required to visit the destination.')),
                ('days', models.IntegerField(blank=True, help_text='Days', null=True)),
                ('nights', models.IntegerField(blank=True, help_text='Nights', null=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Check if the destination is popular among travelers.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(help_text='Select the city where the destination is located.', on_delete=django.db.models.deletion.CASCADE, to='Tours.city')),
                ('country', models.ForeignKey(default='India', help_text='Select the country where the destination is located.', on_delete=django.db.models.deletion.CASCADE, to='Tours.country')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider_names')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(help_text='Select the country where the city is located.', on_delete=django.db.models.deletion.CASCADE, to='Tours.country'),
        ),
    ]
