# Generated by Django 4.1.7 on 2023-03-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(help_text='Select the city where the destination is located.', on_delete=django.db.models.deletion.CASCADE, to='provider.city_data'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(help_text='Select the state where the destination is located.', on_delete=django.db.models.deletion.CASCADE, to='provider.state_data'),
        ),
    ]
