# Generated by Django 4.1.7 on 2023-03-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_alter_destination_city_alter_destination_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
