# Generated by Django 4.1.5 on 2023-03-03 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='provider_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='city_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state_name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='provider.state_data')),
            ],
        ),
        migrations.CreateModel(
            name='Provider_Profile_Model',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='provider.provider_names')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/provider_profile/default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[450, 450], upload_to='provider_profile/')),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10)),
                ('age', models.IntegerField(blank=True, default=15, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_email', models.CharField(blank=True, max_length=50, null=True)),
                ('c_website', models.CharField(blank=True, max_length=50, null=True)),
                ('c_descrip', models.TextField(blank=True, max_length=500, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.city_data')),
            ],
        ),
    ]
